# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.boot_timeout = 500
  # Load Balancer Node
  config.vm.define "loadbalancer" do |kmaster|
    kmaster.vm.box = "centos/7"
    kmaster.vm.hostname = "loadbalancer.example.com"
    kmaster.vm.network "private_network", ip: "192.168.56.100"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "loadbalancer"
      v.memory = 1024
      v.cpus = 1
    end
  end

  MasterCount = 2

  # Kubernetes Master Nodes
  (1..MasterCount).each do |i|
    config.vm.define "kmaster#{i}" do |kmaster|
      kmaster.vm.box = "centos/7"
      kmaster.vm.hostname = "kmaster#{i}.example.com"
      kmaster.vm.network "private_network", ip: "192.168.56.10#{i}"
      kmaster.vm.provider "virtualbox" do |v|
        v.name = "kmaster#{i}"
        v.memory = 2048
        v.cpus = 2
      end
      config.trigger.after [:up, :provision] do |trigger|
        trigger.name = "Config kmaster#{i}"
        trigger.info = "Config kmaster#{i}"
        trigger.run = {path: "../vms_configurations/master.sh"}
      end
    end
  end

  NodeCount = 1

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "kworker#{i}.example.com"
      workernode.vm.network "private_network", ip: "192.168.56.20#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker#{i}"
        v.memory = 1024
        v.cpus = 1
      end
      config.trigger.after [:up, :provision] do |trigger|
        trigger.name = "Config kworker#{i}"
        trigger.info = "Config kworker#{i}"
        trigger.run = {path: "../vms_configurations/worker.sh"}
      end
    end
  end

end
